name: flex_responsive
description: A simple, professional responsive layout solution for Flutter.
version: 0.0.2
homepage: https://github.com/akhankhan/flex_responsive
repository: https://github.com/akhankhan/flex_responsive
documentation: https://github.com/akhankhan/flex_responsive/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
